version: "2"
services:
  mysql-m1:
    build: ./docker/db
    volumes:
      - /var/lib/mysql
    command: --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --sync-binlog=1
      --log-slave-updates=ON
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "21001:3306" # master

  mysql-s1:
    build: ./docker/db
    volumes:
      - /var/lib/mysql
    command: --server-id=2
      --log-bin=mysql-bin
      --binlog-format=ROW
      --sync-binlog=1
      --log-slave-updates=ON
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  toxiproxy:
    image: shopify/toxiproxy
    ports:
      - "22001:22001" # master
      - "22002:22002" # slave
      - "28474:8474"
