global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql global status'
    scrape_interval: 1s
    static_configs:
      - targets:
        - "astrogoat_mysqld_exporter-m1_1:9104"
        - "astrogoat_mysqld_exporter-s1_1:9104"
    params:
      collect[]:
        - global_status
        - heartbeat
